== liblightstone ==

by Kyle Machulis <kyle@nonpolynomial.com>

Nonpolynomial Labs - http://www.nonpolynomial.com

For issues and feature requests, please visit the Github Issues site: https://github.com/qdot/liblightstone/issues

== Description ==

This is a C-based development library for the Lightstone, a Biometric
USB device distributed with the Journey to Wild Divine Relaxation
Software (http://www.wilddivine.com)

liblightstone is released under the BSD License.

== Package Information ==

Source repo and Releases @ http://www.github.com/qdot/liblightstone

== Library Requirements (For Compilation) ==


- CMake (Required on all platforms) - http://www.cmake.org
- HIDAPI - https://github.com/signal11/hidapi

== Build Notes ==

To build liblightstone, make a subdirectory in the source dir (called
whatever you want), then go into that directory and run
"cmake ..". This will generate the project files for your platform
(makefiles for OS X and linux, visual studio for windows). For more
information on project generators, look at the cmake documentation.

== Included Examples ==

- lightstone-test - Tries to open the first lightstone it finds on the
  system, prints output
- lightstone-osc - Only built if libosc is available on the system.
  Transmits OSC messages from the selected lightstone. See program
  options for more info.

== Notes on Compilation and Usage ==

=== Windows ===

No known issues.

=== OS X ===

No known issues.

=== Linux ===

The VID/PID pair will need to be added to udev in order to access the
device without root priviledges. A sample udev file is distributed
with source releases.

== License ==

---------------------
Copyright (c) 2007-2012, Kyle Machulis/Nonpolynomial Labs
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Kyle Machulis/Nonpolynomial Labs nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY Kyle Machulis/Nonpolynomial Labs ''AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Kyle Machulis/Nonpolynomial Labs BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
---------------------
