= liblightstone =

by Kyle Machulis <kyle@nonpolynomial.com>

Nonpolynomial Labs - http://www.nonpolynomial.com

== Description ==

This is a C-based development library for the Lightstone, a Biometric
USB device distributed with the Journey to Wild Divine Relaxation
Software (http://www.wilddivine.com)

liblightstone is released under the BSD License.

== Package Information ==

Project Information @ http://liblightstone.nonpolynomial.com

Source repo @ http://www.github.com/qdot/liblightstone

Releases @ http://www.sourceforge.net/projects/liblightstone

== A Tale of Two Libraries ==

liblightstone comes in two flavors: Win32 and libusb-1.0. The Win32
version uses direct Win32 DDK calls to access the windows HID system,
and reads raw reports from there. libusb-1.0 works for all platforms
currently supporting the library. As of this writing (late December
2009), the libusb-1.0 version of liblightstone has been tested on OS X
and linux.

== Library Requirements (For Compilation) ==


- CMake (Required on all platforms) - http://www.cmake.org
- WDK (Windows Only) - http://www.microsoft.com/whdc/devtools/WDK/default.mspx
- libusb-1.0 (All non-windows platforms) - http://www.libusb.org

== Build Notes ==

To build liblightstone, make a subdirectory in the source dir (called
whatever you want), then go into that directory and run
"cmake ..". This will generate the project files for your platform
(makefiles for OS X and linux, visual studio for windows). For more
information on project generators, look at the cmake documentation.

== Notes on Compilation and Usage ==

=== Mac OS X ===

Assuming you have not installed the Journey to Wild Divine software
and are not installing the dmg version of liblightstone, you will need
to install the "Lightstone OS X Extension" in order to use the
lightstone on OS X. 

Simply copy the LightstoneNullDriver.kext bundle included with the
package to the /System/Library/Extensions directory and reboot.

=== Linux ===

The VID/PID pair of the lightstone will need to be blacklisted on
linux in order to use liblightstone there.

== License ==

---------------------
Copyright (c) 2007-2011, Kyle Machulis/Nonpolynomial Labs
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Kyle Machulis/Nonpolynomial Labs nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY Kyle Machulis/Nonpolynomial Labs ''AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Kyle Machulis/Nonpolynomial Labs BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
---------------------
